--
-- PostgreSQL database dump
--


-- Dumped from database version 16.15 (Debian 16.15-1.pgdg13+2)
-- Dumped by pg_dump version 16.15 (Debian 16.15-1.pgdg13+2)

SET statement_timeout = 0;
SET lock_timeout = 0;
SET idle_in_transaction_session_timeout = 0;
SET client_encoding = 'UTF8';
SET standard_conforming_strings = on;
SELECT pg_catalog.set_config('search_path', '', false);
SET check_function_bodies = false;
SET xmloption = content;
SET client_min_messages = warning;
SET row_security = off;

SET default_tablespace = '';

SET default_table_access_method = heap;

--
-- Name: accounts_credential; Type: TABLE; Schema: public; Owner: -
--

CREATE TABLE public.accounts_credential (
    id integer NOT NULL,
    code uuid NOT NULL,
    name character varying(100) NOT NULL,
    created timestamp with time zone NOT NULL,
    data bytea NOT NULL,
    user_id integer NOT NULL
);


--
-- Name: accounts_credential_id_seq; Type: SEQUENCE; Schema: public; Owner: -
--

ALTER TABLE public.accounts_credential ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.accounts_credential_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- Name: accounts_member; Type: TABLE; Schema: public; Owner: -
--

CREATE TABLE public.accounts_member (
    id integer NOT NULL,
    user_id integer NOT NULL,
    project_id integer NOT NULL,
    transfer_request_date timestamp with time zone,
    role character varying(1) NOT NULL
);


--
-- Name: accounts_member_id_seq; Type: SEQUENCE; Schema: public; Owner: -
--

ALTER TABLE public.accounts_member ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.accounts_member_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- Name: accounts_profile; Type: TABLE; Schema: public; Owner: -
--

CREATE TABLE public.accounts_profile (
    id integer NOT NULL,
    next_report_date timestamp with time zone,
    user_id integer NOT NULL,
    ping_log_limit integer NOT NULL,
    token character varying(128) NOT NULL,
    check_limit integer NOT NULL,
    last_sms_date timestamp with time zone,
    sms_limit integer NOT NULL,
    sms_sent integer NOT NULL,
    sort character varying(20) NOT NULL,
    nag_period interval NOT NULL,
    next_nag_date timestamp with time zone,
    deletion_notice_date timestamp with time zone,
    last_active_date timestamp with time zone,
    call_limit integer NOT NULL,
    calls_sent integer NOT NULL,
    last_call_date timestamp with time zone,
    reports character varying(10) NOT NULL,
    tz character varying(36) NOT NULL,
    theme character varying(10),
    totp character varying(32),
    totp_created timestamp with time zone,
    deletion_scheduled_date timestamp with time zone,
    over_limit_date timestamp with time zone
);


--
-- Name: accounts_profile_id_seq; Type: SEQUENCE; Schema: public; Owner: -
--

ALTER TABLE public.accounts_profile ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.accounts_profile_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- Name: accounts_project; Type: TABLE; Schema: public; Owner: -
--

CREATE TABLE public.accounts_project (
    id integer NOT NULL,
    code uuid NOT NULL,
    name character varying(200) NOT NULL,
    api_key character varying(128) NOT NULL,
    api_key_readonly character varying(128) NOT NULL,
    owner_id integer NOT NULL,
    badge_key character varying(150) NOT NULL,
    ping_key character varying(128),
    show_slugs boolean NOT NULL
);


--
-- Name: accounts_project_id_seq; Type: SEQUENCE; Schema: public; Owner: -
--

ALTER TABLE public.accounts_project ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.accounts_project_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- Name: api_channel; Type: TABLE; Schema: public; Owner: -
--

CREATE TABLE public.api_channel (
    id integer NOT NULL,
    code uuid NOT NULL,
    created timestamp with time zone NOT NULL,
    kind character varying(20) NOT NULL,
    value text NOT NULL,
    email_verified boolean NOT NULL,
    name character varying(100) NOT NULL,
    project_id integer NOT NULL,
    last_error character varying(200) NOT NULL,
    last_notify timestamp with time zone,
    disabled boolean NOT NULL,
    last_notify_duration interval
);


--
-- Name: api_channel_checks; Type: TABLE; Schema: public; Owner: -
--

CREATE TABLE public.api_channel_checks (
    id integer NOT NULL,
    channel_id integer NOT NULL,
    check_id integer NOT NULL
);


--
-- Name: api_channel_checks_id_seq; Type: SEQUENCE; Schema: public; Owner: -
--

ALTER TABLE public.api_channel_checks ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.api_channel_checks_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- Name: api_channel_id_seq; Type: SEQUENCE; Schema: public; Owner: -
--

ALTER TABLE public.api_channel ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.api_channel_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- Name: api_check; Type: TABLE; Schema: public; Owner: -
--

CREATE TABLE public.api_check (
    id integer NOT NULL,
    code uuid NOT NULL,
    last_ping timestamp with time zone,
    alert_after timestamp with time zone,
    status character varying(6) NOT NULL,
    timeout interval NOT NULL,
    name character varying(100) NOT NULL,
    created timestamp with time zone NOT NULL,
    grace interval NOT NULL,
    tags character varying(500) NOT NULL,
    n_pings integer NOT NULL,
    kind character varying(10) NOT NULL,
    schedule character varying(100) NOT NULL,
    tz character varying(36) NOT NULL,
    has_confirmation_link boolean NOT NULL,
    "desc" text NOT NULL,
    last_start timestamp with time zone,
    project_id integer NOT NULL,
    last_duration interval,
    methods character varying(30) NOT NULL,
    manual_resume boolean NOT NULL,
    slug character varying(100) NOT NULL,
    failure_kw character varying(200) NOT NULL,
    filter_body boolean NOT NULL,
    filter_subject boolean NOT NULL,
    success_kw character varying(200) NOT NULL,
    last_start_rid uuid,
    start_kw character varying(200) NOT NULL,
    badge_key uuid NOT NULL,
    filter_default_fail boolean NOT NULL,
    filter_http_body boolean NOT NULL
);


--
-- Name: api_check_id_seq; Type: SEQUENCE; Schema: public; Owner: -
--

ALTER TABLE public.api_check ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.api_check_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- Name: api_flip; Type: TABLE; Schema: public; Owner: -
--

CREATE TABLE public.api_flip (
    id integer NOT NULL,
    created timestamp with time zone NOT NULL,
    processed timestamp with time zone,
    old_status character varying(8) NOT NULL,
    new_status character varying(8) NOT NULL,
    owner_id integer NOT NULL,
    reason character varying(8) NOT NULL
);


--
-- Name: api_flip_id_seq; Type: SEQUENCE; Schema: public; Owner: -
--

ALTER TABLE public.api_flip ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.api_flip_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- Name: api_notification; Type: TABLE; Schema: public; Owner: -
--

CREATE TABLE public.api_notification (
    id integer NOT NULL,
    check_status character varying(6) NOT NULL,
    created timestamp with time zone NOT NULL,
    channel_id integer NOT NULL,
    owner_id integer,
    error character varying(200) NOT NULL,
    code uuid NOT NULL
);


--
-- Name: api_notification_id_seq; Type: SEQUENCE; Schema: public; Owner: -
--

ALTER TABLE public.api_notification ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.api_notification_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- Name: api_ping; Type: TABLE; Schema: public; Owner: -
--

CREATE TABLE public.api_ping (
    id bigint NOT NULL,
    created timestamp with time zone NOT NULL,
    remote_addr inet,
    method character varying(10) NOT NULL,
    ua character varying(200) NOT NULL,
    owner_id integer NOT NULL,
    scheme character varying(10) NOT NULL,
    n integer,
    kind character varying(6),
    exitstatus smallint,
    body_raw bytea,
    object_size integer,
    rid uuid
);


--
-- Name: api_ping_id_seq; Type: SEQUENCE; Schema: public; Owner: -
--

ALTER TABLE public.api_ping ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.api_ping_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- Name: api_tokenbucket; Type: TABLE; Schema: public; Owner: -
--

CREATE TABLE public.api_tokenbucket (
    id integer NOT NULL,
    value character varying(80) NOT NULL,
    tokens double precision NOT NULL,
    updated timestamp with time zone NOT NULL
);


--
-- Name: api_tokenbucket_id_seq; Type: SEQUENCE; Schema: public; Owner: -
--

ALTER TABLE public.api_tokenbucket ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.api_tokenbucket_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- Name: auth_group; Type: TABLE; Schema: public; Owner: -
--

CREATE TABLE public.auth_group (
    id integer NOT NULL,
    name character varying(150) NOT NULL
);


--
-- Name: auth_group_id_seq; Type: SEQUENCE; Schema: public; Owner: -
--

ALTER TABLE public.auth_group ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.auth_group_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- Name: auth_group_permissions; Type: TABLE; Schema: public; Owner: -
--

CREATE TABLE public.auth_group_permissions (
    id integer NOT NULL,
    group_id integer NOT NULL,
    permission_id integer NOT NULL
);


--
-- Name: auth_group_permissions_id_seq; Type: SEQUENCE; Schema: public; Owner: -
--

ALTER TABLE public.auth_group_permissions ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.auth_group_permissions_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- Name: auth_permission; Type: TABLE; Schema: public; Owner: -
--

CREATE TABLE public.auth_permission (
    id integer NOT NULL,
    name character varying(255) NOT NULL,
    content_type_id integer NOT NULL,
    codename character varying(100) NOT NULL
);


--
-- Name: auth_permission_id_seq; Type: SEQUENCE; Schema: public; Owner: -
--

ALTER TABLE public.auth_permission ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.auth_permission_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- Name: auth_user; Type: TABLE; Schema: public; Owner: -
--

CREATE TABLE public.auth_user (
    id integer NOT NULL,
    password character varying(128) NOT NULL,
    last_login timestamp with time zone,
    is_superuser boolean NOT NULL,
    username character varying(150) NOT NULL,
    first_name character varying(150) NOT NULL,
    last_name character varying(150) NOT NULL,
    email character varying(254) NOT NULL,
    is_staff boolean NOT NULL,
    is_active boolean NOT NULL,
    date_joined timestamp with time zone NOT NULL
);


--
-- Name: auth_user_groups; Type: TABLE; Schema: public; Owner: -
--

CREATE TABLE public.auth_user_groups (
    id integer NOT NULL,
    user_id integer NOT NULL,
    group_id integer NOT NULL
);


--
-- Name: auth_user_groups_id_seq; Type: SEQUENCE; Schema: public; Owner: -
--

ALTER TABLE public.auth_user_groups ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.auth_user_groups_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- Name: auth_user_id_seq; Type: SEQUENCE; Schema: public; Owner: -
--

ALTER TABLE public.auth_user ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.auth_user_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- Name: auth_user_user_permissions; Type: TABLE; Schema: public; Owner: -
--

CREATE TABLE public.auth_user_user_permissions (
    id integer NOT NULL,
    user_id integer NOT NULL,
    permission_id integer NOT NULL
);


--
-- Name: auth_user_user_permissions_id_seq; Type: SEQUENCE; Schema: public; Owner: -
--

ALTER TABLE public.auth_user_user_permissions ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.auth_user_user_permissions_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- Name: django_admin_log; Type: TABLE; Schema: public; Owner: -
--

CREATE TABLE public.django_admin_log (
    id integer NOT NULL,
    action_time timestamp with time zone NOT NULL,
    object_id text,
    object_repr character varying(200) NOT NULL,
    action_flag smallint NOT NULL,
    change_message text NOT NULL,
    content_type_id integer,
    user_id integer NOT NULL,
    CONSTRAINT django_admin_log_action_flag_check CHECK ((action_flag >= 0))
);


--
-- Name: django_admin_log_id_seq; Type: SEQUENCE; Schema: public; Owner: -
--

ALTER TABLE public.django_admin_log ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.django_admin_log_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- Name: django_content_type; Type: TABLE; Schema: public; Owner: -
--

CREATE TABLE public.django_content_type (
    id integer NOT NULL,
    app_label character varying(100) NOT NULL,
    model character varying(100) NOT NULL
);


--
-- Name: django_content_type_id_seq; Type: SEQUENCE; Schema: public; Owner: -
--

ALTER TABLE public.django_content_type ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.django_content_type_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- Name: django_migrations; Type: TABLE; Schema: public; Owner: -
--

CREATE TABLE public.django_migrations (
    id integer NOT NULL,
    app character varying(255) NOT NULL,
    name character varying(255) NOT NULL,
    applied timestamp with time zone NOT NULL
);


--
-- Name: django_migrations_id_seq; Type: SEQUENCE; Schema: public; Owner: -
--

ALTER TABLE public.django_migrations ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.django_migrations_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- Name: django_session; Type: TABLE; Schema: public; Owner: -
--

CREATE TABLE public.django_session (
    session_key character varying(40) NOT NULL,
    session_data text NOT NULL,
    expire_date timestamp with time zone NOT NULL
);


--
-- Name: logs_record; Type: TABLE; Schema: public; Owner: -
--

CREATE TABLE public.logs_record (
    id integer NOT NULL,
    created timestamp with time zone NOT NULL,
    name character varying(100) NOT NULL,
    level smallint NOT NULL,
    message text NOT NULL,
    traceback text NOT NULL,
    host character varying(50) NOT NULL,
    CONSTRAINT logs_record_level_check CHECK ((level >= 0))
);


--
-- Name: logs_record_id_seq; Type: SEQUENCE; Schema: public; Owner: -
--

ALTER TABLE public.logs_record ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.logs_record_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- Name: payments_subscription; Type: TABLE; Schema: public; Owner: -
--

CREATE TABLE public.payments_subscription (
    id integer NOT NULL,
    customer_id character varying(36) NOT NULL,
    payment_method_token character varying(35) NOT NULL,
    subscription_id character varying(10) NOT NULL,
    user_id integer NOT NULL,
    plan_id character varying(10) NOT NULL,
    address_id character varying(2) NOT NULL,
    send_invoices boolean NOT NULL,
    plan_name character varying(50) NOT NULL,
    invoice_email character varying(254) NOT NULL,
    next_billing_date date,
    renew_notice_date date,
    setup_date date
);


--
-- Name: payments_subscription_id_seq; Type: SEQUENCE; Schema: public; Owner: -
--

ALTER TABLE public.payments_subscription ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.payments_subscription_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- Name: accounts_credential accounts_credential_code_key; Type: CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.accounts_credential
    ADD CONSTRAINT accounts_credential_code_key UNIQUE (code);


--
-- Name: accounts_credential accounts_credential_pkey; Type: CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.accounts_credential
    ADD CONSTRAINT accounts_credential_pkey PRIMARY KEY (id);


--
-- Name: accounts_member accounts_member_no_duplicates; Type: CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.accounts_member
    ADD CONSTRAINT accounts_member_no_duplicates UNIQUE (user_id, project_id);


--
-- Name: accounts_member accounts_member_pkey; Type: CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.accounts_member
    ADD CONSTRAINT accounts_member_pkey PRIMARY KEY (id);


--
-- Name: accounts_profile accounts_profile_pkey; Type: CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.accounts_profile
    ADD CONSTRAINT accounts_profile_pkey PRIMARY KEY (id);


--
-- Name: accounts_profile accounts_profile_user_id_key; Type: CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.accounts_profile
    ADD CONSTRAINT accounts_profile_user_id_key UNIQUE (user_id);


--
-- Name: accounts_project accounts_project_badge_key_8fe67ffd_uniq; Type: CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.accounts_project
    ADD CONSTRAINT accounts_project_badge_key_8fe67ffd_uniq UNIQUE (badge_key);


--
-- Name: accounts_project accounts_project_code_key; Type: CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.accounts_project
    ADD CONSTRAINT accounts_project_code_key UNIQUE (code);


--
-- Name: accounts_project accounts_project_ping_key_key; Type: CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.accounts_project
    ADD CONSTRAINT accounts_project_ping_key_key UNIQUE (ping_key);


--
-- Name: accounts_project accounts_project_pkey; Type: CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.accounts_project
    ADD CONSTRAINT accounts_project_pkey PRIMARY KEY (id);


--
-- Name: api_channel_checks api_channel_checks_channel_id_check_id_8edbcb0d_uniq; Type: CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.api_channel_checks
    ADD CONSTRAINT api_channel_checks_channel_id_check_id_8edbcb0d_uniq UNIQUE (channel_id, check_id);


--
-- Name: api_channel_checks api_channel_checks_pkey; Type: CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.api_channel_checks
    ADD CONSTRAINT api_channel_checks_pkey PRIMARY KEY (id);


--
-- Name: api_channel api_channel_code_7d0ed173_uniq; Type: CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.api_channel
    ADD CONSTRAINT api_channel_code_7d0ed173_uniq UNIQUE (code);


--
-- Name: api_channel api_channel_pkey; Type: CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.api_channel
    ADD CONSTRAINT api_channel_pkey PRIMARY KEY (id);


--
-- Name: api_check api_check_badge_key_key; Type: CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.api_check
    ADD CONSTRAINT api_check_badge_key_key UNIQUE (badge_key);


--
-- Name: api_check api_check_code_d76cf6a3_uniq; Type: CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.api_check
    ADD CONSTRAINT api_check_code_d76cf6a3_uniq UNIQUE (code);


--
-- Name: api_check api_check_pkey; Type: CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.api_check
    ADD CONSTRAINT api_check_pkey PRIMARY KEY (id);


--
-- Name: api_flip api_flip_pkey; Type: CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.api_flip
    ADD CONSTRAINT api_flip_pkey PRIMARY KEY (id);


--
-- Name: api_notification api_notification_code_08624819_uniq; Type: CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.api_notification
    ADD CONSTRAINT api_notification_code_08624819_uniq UNIQUE (code);


--
-- Name: api_notification api_notification_pkey; Type: CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.api_notification
    ADD CONSTRAINT api_notification_pkey PRIMARY KEY (id);


--
-- Name: api_ping api_ping_pkey; Type: CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.api_ping
    ADD CONSTRAINT api_ping_pkey PRIMARY KEY (id);


--
-- Name: api_tokenbucket api_tokenbucket_pkey; Type: CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.api_tokenbucket
    ADD CONSTRAINT api_tokenbucket_pkey PRIMARY KEY (id);


--
-- Name: api_tokenbucket api_tokenbucket_value_key; Type: CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.api_tokenbucket
    ADD CONSTRAINT api_tokenbucket_value_key UNIQUE (value);


--
-- Name: auth_group auth_group_name_key; Type: CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.auth_group
    ADD CONSTRAINT auth_group_name_key UNIQUE (name);


--
-- Name: auth_group_permissions auth_group_permissions_group_id_permission_id_0cd325b0_uniq; Type: CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.auth_group_permissions
    ADD CONSTRAINT auth_group_permissions_group_id_permission_id_0cd325b0_uniq UNIQUE (group_id, permission_id);


--
-- Name: auth_group_permissions auth_group_permissions_pkey; Type: CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.auth_group_permissions
    ADD CONSTRAINT auth_group_permissions_pkey PRIMARY KEY (id);


--
-- Name: auth_group auth_group_pkey; Type: CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.auth_group
    ADD CONSTRAINT auth_group_pkey PRIMARY KEY (id);


--
-- Name: auth_permission auth_permission_content_type_id_codename_01ab375a_uniq; Type: CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.auth_permission
    ADD CONSTRAINT auth_permission_content_type_id_codename_01ab375a_uniq UNIQUE (content_type_id, codename);


--
-- Name: auth_permission auth_permission_pkey; Type: CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.auth_permission
    ADD CONSTRAINT auth_permission_pkey PRIMARY KEY (id);


--
-- Name: auth_user_groups auth_user_groups_pkey; Type: CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.auth_user_groups
    ADD CONSTRAINT auth_user_groups_pkey PRIMARY KEY (id);


--
-- Name: auth_user_groups auth_user_groups_user_id_group_id_94350c0c_uniq; Type: CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.auth_user_groups
    ADD CONSTRAINT auth_user_groups_user_id_group_id_94350c0c_uniq UNIQUE (user_id, group_id);


--
-- Name: auth_user auth_user_pkey; Type: CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.auth_user
    ADD CONSTRAINT auth_user_pkey PRIMARY KEY (id);


--
-- Name: auth_user_user_permissions auth_user_user_permissions_pkey; Type: CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.auth_user_user_permissions
    ADD CONSTRAINT auth_user_user_permissions_pkey PRIMARY KEY (id);


--
-- Name: auth_user_user_permissions auth_user_user_permissions_user_id_permission_id_14a6b632_uniq; Type: CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.auth_user_user_permissions
    ADD CONSTRAINT auth_user_user_permissions_user_id_permission_id_14a6b632_uniq UNIQUE (user_id, permission_id);


--
-- Name: auth_user auth_user_username_key; Type: CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.auth_user
    ADD CONSTRAINT auth_user_username_key UNIQUE (username);


--
-- Name: django_admin_log django_admin_log_pkey; Type: CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.django_admin_log
    ADD CONSTRAINT django_admin_log_pkey PRIMARY KEY (id);


--
-- Name: django_content_type django_content_type_app_label_model_76bd3d3b_uniq; Type: CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.django_content_type
    ADD CONSTRAINT django_content_type_app_label_model_76bd3d3b_uniq UNIQUE (app_label, model);


--
-- Name: django_content_type django_content_type_pkey; Type: CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.django_content_type
    ADD CONSTRAINT django_content_type_pkey PRIMARY KEY (id);


--
-- Name: django_migrations django_migrations_pkey; Type: CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.django_migrations
    ADD CONSTRAINT django_migrations_pkey PRIMARY KEY (id);


--
-- Name: django_session django_session_pkey; Type: CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.django_session
    ADD CONSTRAINT django_session_pkey PRIMARY KEY (session_key);


--
-- Name: logs_record logs_record_pkey; Type: CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.logs_record
    ADD CONSTRAINT logs_record_pkey PRIMARY KEY (id);


--
-- Name: payments_subscription payments_subscription_pkey; Type: CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.payments_subscription
    ADD CONSTRAINT payments_subscription_pkey PRIMARY KEY (id);


--
-- Name: payments_subscription payments_subscription_user_id_key; Type: CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.payments_subscription
    ADD CONSTRAINT payments_subscription_user_id_key UNIQUE (user_id);


--
-- Name: accounts_credential_user_id_400058ca; Type: INDEX; Schema: public; Owner: -
--

CREATE INDEX accounts_credential_user_id_400058ca ON public.accounts_credential USING btree (user_id);


--
-- Name: accounts_member_project_id_111a002b; Type: INDEX; Schema: public; Owner: -
--

CREATE INDEX accounts_member_project_id_111a002b ON public.accounts_member USING btree (project_id);


--
-- Name: accounts_member_user_id_b994c8b6; Type: INDEX; Schema: public; Owner: -
--

CREATE INDEX accounts_member_user_id_b994c8b6 ON public.accounts_member USING btree (user_id);


--
-- Name: accounts_project_api_key_d70dc8ad; Type: INDEX; Schema: public; Owner: -
--

CREATE INDEX accounts_project_api_key_d70dc8ad ON public.accounts_project USING btree (api_key);


--
-- Name: accounts_project_api_key_d70dc8ad_like; Type: INDEX; Schema: public; Owner: -
--

CREATE INDEX accounts_project_api_key_d70dc8ad_like ON public.accounts_project USING btree (api_key varchar_pattern_ops);


--
-- Name: accounts_project_api_key_readonly_a00a255a; Type: INDEX; Schema: public; Owner: -
--

CREATE INDEX accounts_project_api_key_readonly_a00a255a ON public.accounts_project USING btree (api_key_readonly);


--
-- Name: accounts_project_api_key_readonly_a00a255a_like; Type: INDEX; Schema: public; Owner: -
--

CREATE INDEX accounts_project_api_key_readonly_a00a255a_like ON public.accounts_project USING btree (api_key_readonly varchar_pattern_ops);


--
-- Name: accounts_project_badge_key_8fe67ffd_like; Type: INDEX; Schema: public; Owner: -
--

CREATE INDEX accounts_project_badge_key_8fe67ffd_like ON public.accounts_project USING btree (badge_key varchar_pattern_ops);


--
-- Name: accounts_project_owner_id_9e658e68; Type: INDEX; Schema: public; Owner: -
--

CREATE INDEX accounts_project_owner_id_9e658e68 ON public.accounts_project USING btree (owner_id);


--
-- Name: accounts_project_ping_key_68b63922_like; Type: INDEX; Schema: public; Owner: -
--

CREATE INDEX accounts_project_ping_key_68b63922_like ON public.accounts_project USING btree (ping_key varchar_pattern_ops);


--
-- Name: api_channel_checks_channel_id_0a1351bf; Type: INDEX; Schema: public; Owner: -
--

CREATE INDEX api_channel_checks_channel_id_0a1351bf ON public.api_channel_checks USING btree (channel_id);


--
-- Name: api_channel_checks_check_id_2f0bca8a; Type: INDEX; Schema: public; Owner: -
--

CREATE INDEX api_channel_checks_check_id_2f0bca8a ON public.api_channel_checks USING btree (check_id);


--
-- Name: api_channel_project_id_1ae78745; Type: INDEX; Schema: public; Owner: -
--

CREATE INDEX api_channel_project_id_1ae78745 ON public.api_channel USING btree (project_id);


--
-- Name: api_check_aa_not_down; Type: INDEX; Schema: public; Owner: -
--

CREATE INDEX api_check_aa_not_down ON public.api_check USING btree (alert_after) WHERE (NOT ((status)::text = 'down'::text));


--
-- Name: api_check_project_id_2af7b4db; Type: INDEX; Schema: public; Owner: -
--

CREATE INDEX api_check_project_id_2af7b4db ON public.api_check USING btree (project_id);


--
-- Name: api_check_project_slug; Type: INDEX; Schema: public; Owner: -
--

CREATE INDEX api_check_project_slug ON public.api_check USING btree (project_id, slug);


--
-- Name: api_flip_not_processed; Type: INDEX; Schema: public; Owner: -
--

CREATE INDEX api_flip_not_processed ON public.api_flip USING btree (processed) WHERE (processed IS NULL);


--
-- Name: api_flip_owner_created; Type: INDEX; Schema: public; Owner: -
--

CREATE INDEX api_flip_owner_created ON public.api_flip USING btree (owner_id, created);


--
-- Name: api_flip_owner_id_4ccc8bee; Type: INDEX; Schema: public; Owner: -
--

CREATE INDEX api_flip_owner_id_4ccc8bee ON public.api_flip USING btree (owner_id);


--
-- Name: api_notification_channel_id_4df05d31; Type: INDEX; Schema: public; Owner: -
--

CREATE INDEX api_notification_channel_id_4df05d31 ON public.api_notification USING btree (channel_id);


--
-- Name: api_notification_owner_id_9b970e8a; Type: INDEX; Schema: public; Owner: -
--

CREATE INDEX api_notification_owner_id_9b970e8a ON public.api_notification USING btree (owner_id);


--
-- Name: api_ping_owner_id_e4ea931d; Type: INDEX; Schema: public; Owner: -
--

CREATE INDEX api_ping_owner_id_e4ea931d ON public.api_ping USING btree (owner_id);


--
-- Name: api_tokenbucket_value_dfd98882_like; Type: INDEX; Schema: public; Owner: -
--

CREATE INDEX api_tokenbucket_value_dfd98882_like ON public.api_tokenbucket USING btree (value varchar_pattern_ops);


--
-- Name: auth_group_name_a6ea08ec_like; Type: INDEX; Schema: public; Owner: -
--

CREATE INDEX auth_group_name_a6ea08ec_like ON public.auth_group USING btree (name varchar_pattern_ops);


--
-- Name: auth_group_permissions_group_id_b120cbf9; Type: INDEX; Schema: public; Owner: -
--

CREATE INDEX auth_group_permissions_group_id_b120cbf9 ON public.auth_group_permissions USING btree (group_id);


--
-- Name: auth_group_permissions_permission_id_84c5c92e; Type: INDEX; Schema: public; Owner: -
--

CREATE INDEX auth_group_permissions_permission_id_84c5c92e ON public.auth_group_permissions USING btree (permission_id);


--
-- Name: auth_permission_content_type_id_2f476e4b; Type: INDEX; Schema: public; Owner: -
--

CREATE INDEX auth_permission_content_type_id_2f476e4b ON public.auth_permission USING btree (content_type_id);


--
-- Name: auth_user_groups_group_id_97559544; Type: INDEX; Schema: public; Owner: -
--

CREATE INDEX auth_user_groups_group_id_97559544 ON public.auth_user_groups USING btree (group_id);


--
-- Name: auth_user_groups_user_id_6a12ed8b; Type: INDEX; Schema: public; Owner: -
--

CREATE INDEX auth_user_groups_user_id_6a12ed8b ON public.auth_user_groups USING btree (user_id);


--
-- Name: auth_user_user_permissions_permission_id_1fbb5f2c; Type: INDEX; Schema: public; Owner: -
--

CREATE INDEX auth_user_user_permissions_permission_id_1fbb5f2c ON public.auth_user_user_permissions USING btree (permission_id);


--
-- Name: auth_user_user_permissions_user_id_a95ead1b; Type: INDEX; Schema: public; Owner: -
--

CREATE INDEX auth_user_user_permissions_user_id_a95ead1b ON public.auth_user_user_permissions USING btree (user_id);


--
-- Name: auth_user_username_6821ab7c_like; Type: INDEX; Schema: public; Owner: -
--

CREATE INDEX auth_user_username_6821ab7c_like ON public.auth_user USING btree (username varchar_pattern_ops);


--
-- Name: django_admin_log_content_type_id_c4bce8eb; Type: INDEX; Schema: public; Owner: -
--

CREATE INDEX django_admin_log_content_type_id_c4bce8eb ON public.django_admin_log USING btree (content_type_id);


--
-- Name: django_admin_log_user_id_c564eba6; Type: INDEX; Schema: public; Owner: -
--

CREATE INDEX django_admin_log_user_id_c564eba6 ON public.django_admin_log USING btree (user_id);


--
-- Name: django_session_expire_date_a5c62663; Type: INDEX; Schema: public; Owner: -
--

CREATE INDEX django_session_expire_date_a5c62663 ON public.django_session USING btree (expire_date);


--
-- Name: django_session_session_key_c0390e0f_like; Type: INDEX; Schema: public; Owner: -
--

CREATE INDEX django_session_session_key_c0390e0f_like ON public.django_session USING btree (session_key varchar_pattern_ops);


--
-- Name: accounts_credential accounts_credential_user_id_400058ca_fk_auth_user_id; Type: FK CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.accounts_credential
    ADD CONSTRAINT accounts_credential_user_id_400058ca_fk_auth_user_id FOREIGN KEY (user_id) REFERENCES public.auth_user(id) DEFERRABLE INITIALLY DEFERRED;


--
-- Name: accounts_member accounts_member_project_id_111a002b_fk_accounts_project_id; Type: FK CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.accounts_member
    ADD CONSTRAINT accounts_member_project_id_111a002b_fk_accounts_project_id FOREIGN KEY (project_id) REFERENCES public.accounts_project(id) DEFERRABLE INITIALLY DEFERRED;


--
-- Name: accounts_member accounts_member_user_id_b994c8b6_fk_auth_user_id; Type: FK CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.accounts_member
    ADD CONSTRAINT accounts_member_user_id_b994c8b6_fk_auth_user_id FOREIGN KEY (user_id) REFERENCES public.auth_user(id) DEFERRABLE INITIALLY DEFERRED;


--
-- Name: accounts_profile accounts_profile_user_id_49a85d32_fk_auth_user_id; Type: FK CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.accounts_profile
    ADD CONSTRAINT accounts_profile_user_id_49a85d32_fk_auth_user_id FOREIGN KEY (user_id) REFERENCES public.auth_user(id) DEFERRABLE INITIALLY DEFERRED;


--
-- Name: accounts_project accounts_project_owner_id_9e658e68_fk_auth_user_id; Type: FK CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.accounts_project
    ADD CONSTRAINT accounts_project_owner_id_9e658e68_fk_auth_user_id FOREIGN KEY (owner_id) REFERENCES public.auth_user(id) DEFERRABLE INITIALLY DEFERRED;


--
-- Name: api_channel_checks api_channel_checks_channel_id_0a1351bf_fk_api_channel_id; Type: FK CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.api_channel_checks
    ADD CONSTRAINT api_channel_checks_channel_id_0a1351bf_fk_api_channel_id FOREIGN KEY (channel_id) REFERENCES public.api_channel(id) DEFERRABLE INITIALLY DEFERRED;


--
-- Name: api_channel_checks api_channel_checks_check_id_2f0bca8a_fk_api_check_id; Type: FK CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.api_channel_checks
    ADD CONSTRAINT api_channel_checks_check_id_2f0bca8a_fk_api_check_id FOREIGN KEY (check_id) REFERENCES public.api_check(id) DEFERRABLE INITIALLY DEFERRED;


--
-- Name: api_channel api_channel_project_id_1ae78745_fk_accounts_project_id; Type: FK CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.api_channel
    ADD CONSTRAINT api_channel_project_id_1ae78745_fk_accounts_project_id FOREIGN KEY (project_id) REFERENCES public.accounts_project(id) DEFERRABLE INITIALLY DEFERRED;


--
-- Name: api_check api_check_project_id_2af7b4db_fk_accounts_project_id; Type: FK CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.api_check
    ADD CONSTRAINT api_check_project_id_2af7b4db_fk_accounts_project_id FOREIGN KEY (project_id) REFERENCES public.accounts_project(id) DEFERRABLE INITIALLY DEFERRED;


--
-- Name: api_flip api_flip_owner_id_4ccc8bee_fk_api_check_id; Type: FK CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.api_flip
    ADD CONSTRAINT api_flip_owner_id_4ccc8bee_fk_api_check_id FOREIGN KEY (owner_id) REFERENCES public.api_check(id) DEFERRABLE INITIALLY DEFERRED;


--
-- Name: api_notification api_notification_channel_id_4df05d31_fk_api_channel_id; Type: FK CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.api_notification
    ADD CONSTRAINT api_notification_channel_id_4df05d31_fk_api_channel_id FOREIGN KEY (channel_id) REFERENCES public.api_channel(id) DEFERRABLE INITIALLY DEFERRED;


--
-- Name: api_notification api_notification_owner_id_9b970e8a_fk_api_check_id; Type: FK CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.api_notification
    ADD CONSTRAINT api_notification_owner_id_9b970e8a_fk_api_check_id FOREIGN KEY (owner_id) REFERENCES public.api_check(id) DEFERRABLE INITIALLY DEFERRED;


--
-- Name: api_ping api_ping_owner_id_e4ea931d_fk_api_check_id; Type: FK CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.api_ping
    ADD CONSTRAINT api_ping_owner_id_e4ea931d_fk_api_check_id FOREIGN KEY (owner_id) REFERENCES public.api_check(id) DEFERRABLE INITIALLY DEFERRED;


--
-- Name: auth_group_permissions auth_group_permissio_permission_id_84c5c92e_fk_auth_perm; Type: FK CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.auth_group_permissions
    ADD CONSTRAINT auth_group_permissio_permission_id_84c5c92e_fk_auth_perm FOREIGN KEY (permission_id) REFERENCES public.auth_permission(id) DEFERRABLE INITIALLY DEFERRED;


--
-- Name: auth_group_permissions auth_group_permissions_group_id_b120cbf9_fk_auth_group_id; Type: FK CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.auth_group_permissions
    ADD CONSTRAINT auth_group_permissions_group_id_b120cbf9_fk_auth_group_id FOREIGN KEY (group_id) REFERENCES public.auth_group(id) DEFERRABLE INITIALLY DEFERRED;


--
-- Name: auth_permission auth_permission_content_type_id_2f476e4b_fk_django_co; Type: FK CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.auth_permission
    ADD CONSTRAINT auth_permission_content_type_id_2f476e4b_fk_django_co FOREIGN KEY (content_type_id) REFERENCES public.django_content_type(id) DEFERRABLE INITIALLY DEFERRED;


--
-- Name: auth_user_groups auth_user_groups_group_id_97559544_fk_auth_group_id; Type: FK CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.auth_user_groups
    ADD CONSTRAINT auth_user_groups_group_id_97559544_fk_auth_group_id FOREIGN KEY (group_id) REFERENCES public.auth_group(id) DEFERRABLE INITIALLY DEFERRED;


--
-- Name: auth_user_groups auth_user_groups_user_id_6a12ed8b_fk_auth_user_id; Type: FK CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.auth_user_groups
    ADD CONSTRAINT auth_user_groups_user_id_6a12ed8b_fk_auth_user_id FOREIGN KEY (user_id) REFERENCES public.auth_user(id) DEFERRABLE INITIALLY DEFERRED;


--
-- Name: auth_user_user_permissions auth_user_user_permi_permission_id_1fbb5f2c_fk_auth_perm; Type: FK CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.auth_user_user_permissions
    ADD CONSTRAINT auth_user_user_permi_permission_id_1fbb5f2c_fk_auth_perm FOREIGN KEY (permission_id) REFERENCES public.auth_permission(id) DEFERRABLE INITIALLY DEFERRED;


--
-- Name: auth_user_user_permissions auth_user_user_permissions_user_id_a95ead1b_fk_auth_user_id; Type: FK CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.auth_user_user_permissions
    ADD CONSTRAINT auth_user_user_permissions_user_id_a95ead1b_fk_auth_user_id FOREIGN KEY (user_id) REFERENCES public.auth_user(id) DEFERRABLE INITIALLY DEFERRED;


--
-- Name: django_admin_log django_admin_log_content_type_id_c4bce8eb_fk_django_co; Type: FK CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.django_admin_log
    ADD CONSTRAINT django_admin_log_content_type_id_c4bce8eb_fk_django_co FOREIGN KEY (content_type_id) REFERENCES public.django_content_type(id) DEFERRABLE INITIALLY DEFERRED;


--
-- Name: django_admin_log django_admin_log_user_id_c564eba6_fk_auth_user_id; Type: FK CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.django_admin_log
    ADD CONSTRAINT django_admin_log_user_id_c564eba6_fk_auth_user_id FOREIGN KEY (user_id) REFERENCES public.auth_user(id) DEFERRABLE INITIALLY DEFERRED;


--
-- Name: payments_subscription payments_subscription_user_id_1b2156fc_fk_auth_user_id; Type: FK CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.payments_subscription
    ADD CONSTRAINT payments_subscription_user_id_1b2156fc_fk_auth_user_id FOREIGN KEY (user_id) REFERENCES public.auth_user(id) DEFERRABLE INITIALLY DEFERRED;


--
-- PostgreSQL database dump complete
--


