CREATE TABLE serial_pk (
    id serial PRIMARY KEY,
    name text NOT NULL
);

CREATE TABLE identity_always (
    id integer GENERATED ALWAYS AS IDENTITY PRIMARY KEY,
    name text NOT NULL
);

CREATE TABLE identity_by_default (
    id integer GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    name text NOT NULL
);
