[package]
name = "feint-core"
version.workspace = true
edition.workspace = true
license.workspace = true
description.workspace = true
keywords.workspace = true
categories.workspace = true

[dependencies]
tokio = { workspace = true }
tokio-postgres = { workspace = true }
deadpool-postgres = { workspace = true }
serde = { workspace = true }
serde_yaml_ng = { workspace = true }
serde_json = { workspace = true }
fake = { workspace = true }
rand = { workspace = true }
rand_chacha = { workspace = true }
petgraph = { workspace = true }
blake3 = { workspace = true }
uuid = { workspace = true }
chrono = { workspace = true }
rust_decimal = { workspace = true }
thiserror = { workspace = true }
bytes = "1"
fallible-iterator = "0.2"
postgres-types = { version = "0.2", features = ["with-uuid-1", "with-chrono-0_4", "with-serde_json-1"] }
postgres-protocol = "0.6"
rustls = { workspace = true }
tokio-postgres-rustls = { workspace = true }
regex = { workspace = true }
bincode = { workspace = true }
flate2 = { workspace = true }
futures-util = { workspace = true }

[dev-dependencies]
testcontainers = { workspace = true }
testcontainers-modules = { workspace = true }
rstest = { workspace = true }
tokio = { workspace = true, features = ["rt-multi-thread", "macros", "test-util"] }
dtor = { workspace = true }
